version: '3'

services:
  rent_backend:
    image: rent_backend
    build:
      context: ./Backend/RentYourHome
    container_name: rent-backend
    depends_on: 
     - db
    command: ["dotnet", "ef" , "database update"]
    ports:
      - "9090:9090"
    networks:
      - rent-network

  rent-frontend:
    container_name: rent-frontend
    image: rent_frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - rent-network
    depends_on:
      - rent_backend
    environment:
      BACKEND_URL: 'http://rent_backend:9090'
  db:
    image: mcr.microsoft.com/mssql/server
    container_name: db
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=yourStrong(!)Password
    ports:
      - "1435:1433"
networks:
  rent-network:

